hosts:
  "localhost:8081":
    listen:
      port: 8081
      ssl:
        certificate-file: /workspace/certs/p384.crt
        key-file: /workspace/certs/p384.key
    listen:
      port: 8444
      type: quic
      ssl:
        certificate-file: /workspace/certs/p384.crt
        key-file: /workspace/certs/p384.key
    paths:
      "/":
        file.dir: /workspace/examples/doc_root
