listen: 8085
listen:
  port: 8445
  ssl:
    certificate-file: /workspace/certs/rsa.crt
    key-file: /workspace/certs/rsa.key
hosts:
  "localhost":
    paths:
      "/":
        proxy.reverse.url: http://127.0.0.1:9190